{"name": "test_01", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 4", "trace": "self = <pytest_demo.Test object at 0x000001FE21158BC8>\n\n    def test_01(self):\n>       assert 3 == 4\nE       assert 3 == 4\n\npytest_demo.py:6: AssertionError"}, "start": 1605171254641, "stop": 1605171254642, "uuid": "764da00d-114d-43a1-9ca0-0974a558198b", "historyId": "b56b54832b4871738f1fb4fc2775b43d", "testCaseId": "af1e41882c93c8999d70fa66c44dfee0", "fullName": "pytest_demo.Test#test_01", "labels": [{"name": "suite", "value": "pytest_demo"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "WIN-0HDPTRO9OLO"}, {"name": "thread", "value": "38236-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest_demo"}]}